services:
  postgres:
    image: postgres:15.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=bookmark
    ports:
      - '5432:5432'
    volumes: 
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: